### ISSUE TITLE
Not Showing 5GHz Wifi

### ISSUE THREAD

**Issue by staostd** [halogenOS/android_device_oneplus_oneplus2#21]
Device: oneplus 2
version 20170624
problem: not showing 5.0GHz wifi 

thank you!

**Comment by xdevs23** [comment]
@MSF-Jarvis any idea why it doesn't show up

**Comment by ponytojas** [comment]
@staostd

**Comment by xdevs23** [comment]
![img_20170703_151735](https://user-images.githubusercontent.com/6959245/27794532-d044b878-6002-11e7-87b3-c896d3eaf910.jpg)
Pic by @ponytojas 

Seems that 5G is working automatically, no reason for adding the setting, is there one?

**Comment by staostd** [comment]
sorry for bothering,after I reboot my router, everything is fine.
