### ISSUE TITLE
Video recording does not work

### ISSUE THREAD

**Issue by Th30wl** [halogenOS/android_device_oneplus_oneplus2#23]
Video recording seems to work only the first time after boot. Afterwards it records video but never saves it.
System info attached.
![rgmpx2l](https://user-images.githubusercontent.com/30597832/28781235-aaab76ca-7609-11e7-99e5-550a2b6c0a8f.png)

**Comment by xdevs23** [comment]
It's a known issue, thanks for reporting anyways.
