### ISSUE TITLE
Some audio commits

### ISSUE THREAD

**Issue by aviraxp** [halogenOS/android_device_oneplus_oneplus2#5]
From AOSPA

https://github.com/AOSPA/android_device_oneplus_oneplus2/commit/88b3db7fc2ef16732fed252ba59f044a1dc5fb0d

https://github.com/AOSPA/android_device_oneplus_oneplus2/commit/c0dd4dde696cc3e1e115c16c6a497103a7a8cc3a

**Comment by aviraxp** [comment]
How about cherry-picking them？

**Comment by aviraxp** [comment]
The latter one fixed a weird bug for me.

**Comment by xdevs23** [comment]
We already have the first change..... I think.

**Comment by aviraxp** [comment]
Ah yes, you are right.

**Comment by xdevs23** [comment]
Done.
