### ISSUE TITLE
Mess.

### ISSUE THREAD

**Issue by regalstreak** [halogenOS/android_device_oneplus_oneplus2#7]
I'm gonna do a rework on this now.

**Comment by msfjarvis** [comment]
Good, I've forced push the fixes tho

**Comment by regalstreak** [comment]
Thanks for that. Will make my work easier.

CC: @xdevs23

**Comment by xdevs23** [comment]
Yeah, thanks @MSF-Jarvis

**Comment by regalstreak** [comment]
Kernel rework needed?

**Comment by msfjarvis** [comment]
I guess no, I'm not seeing anyone report kernel panics yet

**Comment by xdevs23** [comment]
Kernel is fine so far, rework would mean taking pure CAF MSM kernel and setting it up for OP2.

**Comment by xdevs23** [comment]
But if you do that, take the latest kernel version possible.

**Comment by regalstreak** [comment]
OK i'm doing it here: https://github.com/regalstreak/android_device_oneplus_oneplus2/
