### ISSUE TITLE
Whatsapp messages not recieved when screen off (Only on WIFI) (bug started on 0.4.1-beta and still present)

### ISSUE THREAD

**Issue by keessonnema** [halogenOS/android_device_oneplus_oneplus2#9]
Since 0.4.1-beta I have this bug that Whatsapp messages aren't recieving when the screen is off and I'm on WIFI (both at work and at home).

As soon as I press the powerbutton all my messages are coming in.

I heard more people have this problem, but I don't know what would be the cause.

**Comment by keessonnema** [comment]
Maybe this change causes it: https://github.com/halogenOS/android_device_oneplus_oneplus2/commit/921a986bedd0f2cb3319959d2850c269402699ed

**Comment by msfjarvis** [comment]
Can you download stuff over WiFi with screen off?

**Comment by keessonnema** [comment]
Hmm I tried downloading a zip file, but as soon s the screen gone off a couple of seconds later the download paused for some reason. So I guess it's a WIFI background problem. Maybe it's the doze improvement?

**Comment by aviraxp** [comment]
Not doze issue I guess. Every ROM for Oneplus2 has this commit.

**Comment by msfjarvis** [comment]
This commit does not touch Doze, so no, it indeed is an issue with Doze.

**Comment by aviraxp** [comment]
Then almost all Oneplus2 ROM will have the issue.

Then you can try to disable OneplusDoze and see what happens.

**Comment by msfjarvis** [comment]
I'll look at it later

**Comment by xdevs23** [comment]
Can't keep up, too much stuff going on WHILE I AM NOT HERE.

**Comment by msfjarvis** [comment]
@xdevs23, I'm not seeing what stuff is going on here without you. Whine
about it on our Telegram please.

**Comment by xdevs23** [comment]
I'm just saying that most of the time I am here, nobody is creating issues etc. but whenever I am not here, y'all are spamming :joy:

**Comment by msfjarvis** [comment]
Ahh them nasty bug hunters! I thought code wise 😌

**Comment by keessonnema** [comment]
Already a fix for the wifi problem?

**Comment by msfjarvis** [comment]
No we don't have a fix for this right now, @aviraxp's suggestion to just go
ahead and remove doze sounds too aggressive to me. I'll just wait it out
for Simao to debug this properly.

**Comment by xdevs23** [comment]
For me it works... i think.
didn't get any problems on that yet.

But N is coming soon anyways so it should be better there.

**Comment by xdevs23** [comment]
If it persists, we'll revert that commit

**Comment by keessonnema** [comment]
N will be different anyway. If it's the same, revert it :)

**Comment by xdevs23** [comment]
Works in Nougat, afaik. 
Repoen if happens again.
